### ISSUE TITLE
好像获取到的url不能直接进到空间或者邮箱？

### ISSUE THREAD

**Issue by him95** [sun589/QQkey_Tool#11]
本地测试了一下，获取的链接点进去还是跳转回登录确认页，请问这个是正常的吗？

**Comment by sun589** [comment]
看下clientkey有没有获取成功,如果是None就说明没获取到key,可能是不支持当前QQ版本,目前已知不支持的版本为9.7.23

**Comment by him95** [comment]
> 看下clientkey有没有获取成功,如果是None就说明没获取到key,可能是不支持当前QQ版本,目前已知不支持的版本为9.7.23

那应该是了，除了qq号其他都是none。感谢解答

**Comment by sun589** [comment]
可以提供一下qq版本吗,方便我去适配它

**Comment by siukka** [comment]
不好意思，现在才看到。当时我用的是tim，没留意版本号，但是确定是9月初的最新版
