### ISSUE TITLE
新版的ntqq 9.9跟qq9.7支持吗？

### ISSUE THREAD

**Issue by blackchicken20** [sun589/QQkey_Tool#12]
自己想用C++移植一份。
谢谢作者。

9.7 应该是 qq9.7.23 官网能下到的版本。

我自己调试下来好像9.7.23有什么特殊的东西，导致没法post，具体原因不知道。

**Comment by sun589** [comment]
是这样的,9.7.2x版本有神秘原因导致无法post,目前这有这个版本有问题,其他的未知,不过9.9.xx这种最新支持的

**Comment by blackchicken20** [comment]
> 是这样的,9.7.2x版本有神秘原因导致无法post,目前只有这个版本有问题,其他的未知,不过9.9.xx这种最新支持的

神秘原因具体是什么？可以透露吗？

**Comment by sun589** [comment]
没啥,我也不知道,应该是做反爬了,试过把所有headers和cookie带上,就是死活发不了请求

**Comment by sun589** [comment]
对于网页就可以请求成功我也不清楚,等有人去逆向js吧...

**Comment by blackchicken20** [comment]
> 对于网页就可以请求成功我也不清楚,等有人去逆向js吧...

目测是跟ssl协议有关系，因为ie浏览器也不行，唯有谷歌浏览器可以，估计与js无关。

**Comment by sun589** [comment]
是吗?我都没发现,那就等有人把他研究明白吧(

**Comment by sun589** [comment]
ie8可以,我刚试了

**Comment by blackchicken20** [comment]
> ie8可以,我刚试了

这就很神奇了，有些电脑他ie浏览器不行，但是谷歌就有这个快速登陆。我再研究看看，有消息再同步到这。
