### ISSUE TITLE
After the Trojan is generated, the download system cannot find the specified file

### ISSUE THREAD

**Issue by BOBOTSB** [sun589/QQkey_Tool#13]
After the Trojan is generated, the download system cannot find the specified file

**Comment by sun589** [comment]
让我们说中文
描述复现过程+截下图屑屑

**Comment by BOBOTSB** [comment]
木马生成后，下载系统找不到指定的文件
![b0dd26dc4f2dd75dca04c4e4d3295d05](https://github.com/user-attachments/assets/1e3b370c-29b9-48b2-a546-2f95e9372ed9)

**Comment by sun589** [comment]
说下复现过程,比如先xxx在xxx再xxx再生成

**Comment by sun589** [comment]
信息是正常输入的吗

**Comment by BOBOTSB** [comment]
正常输入的，点生成之后就显示系统找不到指定的文件

**Comment by BOBOTSB** [comment]
这种情况怎么处理.....

**Comment by sun589** [comment]
你把程序所在的文件夹截个图我看下

**Comment by sun589** [comment]
看下有没有data文件夹,进去截个图然后再点开Scripts文件夹截图我看下

**Comment by sun589** [comment]
如果不行可以手动解压搭建包之后把解压的文件夹重命名为data看看

**Comment by sun589** [comment]
看下有没有勾上自定义图标这些东西啥的

**Comment by sun589** [comment]
待会更新版本,你到时候去看看新的行不行,不行你就发日志

**Comment by sun589** [comment]
还在吗,如果还不回复就关闭了....
