### ISSUE TITLE
下载了exe文件点开没反应

### ISSUE THREAD

**Issue by 319707767** [sun589/QQkey_Tool#18]
### 检查项

- [X] 我已在 [Issues](https://github.com/sun589/QQkey_Tool/issues) 中搜索，确认了这一建议从未被人提及过
- [X] 在 [Release](https://github.com/sun589/QQkey_Tool/releases) 升级至最新版本后, 发现我要说的仍然不存在

### 描述

我下载了作者的exe文件 点开了并没有反应

**Comment by sun589** [comment]
打开可能会慢点,一般最慢十几秒就可以了,如果不行看下文件名是不是有中文,改成纯英文看看

**Comment by 319707767** [comment]
这个为什么显示找不到搭建包
![1730939769234](https://github.com/user-attachments/assets/0045b015-5eaf-4874-94ea-5430573f650b)

**Comment by sun589** [comment]
zip不用解压,留在目录就可以了,程序会自动解压的

**Comment by 319707767** [comment]
![501d75f483de26c71239d3280321b585](https://github.com/user-attachments/assets/b3284bb9-a5fc-4794-978c-42c35a314d6d)
为什么我获取不到信息？

**Comment by 319707767** [comment]
我使用的是新版QQ9

**Comment by sun589** [comment]
报下QQ版本,我去看看

**Comment by sun589** [comment]
说详细的,比如9.9.15
