### ISSUE TITLE
大佬可不可以打包一个只输出clientkey的程序，求求了QAQ

### ISSUE THREAD

**Issue by mah1618** [sun589/QQkey_Tool#2]
大佬可不可以打包一个只输出clientkey的程序，求求了QAQ

**Comment by sun589** [comment]
没事:))))))))))))
你是第3位看到此项目的,感谢你宝贵的star:))))))))))))))))))))))

**Comment by sun589** [comment]
get_clientkey源码上传了,需要学习可以来看眼:)
