### ISSUE TITLE
QQ扫码登录器

### ISSUE THREAD

**Issue by xuan06zyx** [sun589/QQkey_Tool#24]
### 检查项

- [X] 我已在 [Issues](https://github.com/sun589/QQkey_Tool/issues) 中搜索，确认了这一建议从未被人提及过
- [X] 在 [Release](https://github.com/sun589/QQkey_Tool/releases) 升级至最新版本后, 发现我要说的仍然不存在

### 描述

未来会做到该项目里吗，或者说有没有思路可以提供一下？

**Comment by sun589** [comment]
额，有点没懂意思(?
详细说说项目指的哪个 思路又指的哪个

**Comment by sun589** [comment]
你是指[PyQQSkeyTool](https://github.com/sun589/PyQQSkeyTool)吗？

**Comment by xuan06zyx** [comment]
就是我现在想要一个可以在电脑上扫码登录诸如WeGame之类的程序，因为我经常有将游戏号借出去的需求但是手机不在手边。
以及我可能会在此基础上另外开发一个捕获b站直播流的QQ登录扫码器

**Comment by sun589** [comment]
没什么思路...

**Comment by sun589** [comment]
想到了再来找你吧
