### ISSUE TITLE
木马从内存中直接获取宿主机信息

### ISSUE THREAD

**Issue by Vekor64** [sun589/QQkey_Tool#26]
### 检查项

- [X] 我已在 [Issues](https://github.com/sun589/QQkey_Tool/issues) 中搜索，确认了这一建议从未被人提及过
- [X] 在 [Release](https://github.com/sun589/QQkey_Tool/releases) 升级至最新版本后, 发现我要说的仍然不存在

### 描述

有没有打算让木马直接从内存中获取宿主机的Uin，skey。我去年用易语言开发过这样的木马，只在怀旧版上成功了，新版的QQ还没有头绪，想参考一下大佬代码，感觉从访问接口获取有点繁琐

**Comment by sun589** [comment]
没有 :P
我主要学爬虫的，hook内存注入啥啥啥都不太了解(
