### ISSUE TITLE
请问我设置的有问题吗 邮箱收不到

### ISSUE THREAD

**Issue by 1214294719** [sun589/QQkey_Tool#3]

**Comment by sun589** [comment]
请问下问题解决了吗,如果未解决检查任务管理器进程是否正常退出,如果还是不行再说下

**Comment by sun589** [comment]
获取需要半分钟到一分钟,若超过一分钟可能是工具未获取到key或者smtp服务器设置有问题,在我这边用163是可以的

**Comment by sun589** [comment]
补充下,检查下qq是否登录或者是否打开,木马会一直等待直到可以获取到key,基本上不存在获取不到的情况,QQ9.9.15可正常获取发送

**Comment by audwh** [comment]
木马怎么做的呀，是要把木马发给别人吗，还是怎么弄
