### ISSUE TITLE
木马功能打不开，安装了搭建包也放在了同一目录

### ISSUE THREAD

**Issue by audwh** [sun589/QQkey_Tool#4]
我是在虚拟机上运行的，但是感觉没事吧，为什么下载了搭建包还是打不开，解压了，求回感谢
![Uploading 批注 2024-08-17 083256.png…]()

**Comment by audwh** [comment]
还有就是获取key，那个二维码怎么用的呀，真不知道咋用，是用手机qq扫码，还是怎么弄，希望给个详细的教程，万分感谢

**Comment by audwh** [comment]
是木马那个功能

**Comment by sun589** [comment]
1.这个软件无毒无害且开源,可放心使用
2.搭建包不需要解压,只需放在与程序同目录即可
关于教程的话,目前我正在写,到时候写好提示你一声,感谢star:))))))))))

**Comment by sun589** [comment]
那个提示框显示什么,是文件不完整还是不存在,图片我打不开,把窗口提示给一下,谢谢

**Comment by sun589** [comment]
我这边vmware虚拟机内测试也是可以的,看下文件名是不是Tools(区分大小写),然后还有问题的话再说

**Comment by audwh** [comment]
搭建包不用解压吗，好像还是不行，提示就是没有安装搭建包，但是我也放在一个目录了

**Comment by audwh** [comment]
感谢已经解决了，原来是文件名错了，谢谢

**Comment by audwh** [comment]
但是好像不会用（哭死），还是希望有教程

**Comment by sun589** [comment]
解决了就好,目前在写教程文档:)
