### ISSUE TITLE
二维码无法使用手机直接扫描，需要后置摄像才行

### ISSUE THREAD

**Issue by audwh** [sun589/QQkey_Tool#5]
有解决办法吗

**Comment by sun589** [comment]
问下,我没有读懂你的意思,你是指无法使用手机扫描吗

**Comment by audwh** [comment]
> 问下,我没有读懂你的意思,你是指无法使用手机扫描吗

不能扫描QQ保存在QQ相册的二维码，必须用后置扫描

**Comment by audwh** [comment]
还有就是开放QQ空间貌似没效果，不知道是不是操作问题

**Comment by sun589** [comment]
正常的,QQ一般就是默认禁止从相册扫描二维码,这是通病 开放空间的话我看下

**Comment by sun589** [comment]
开放空间正常的,你看下扫描二维码下面是不是有个qun.qq.com,再看看开放空间是不是有个(qzone)文字,你需要将那个切换成qzone.qq.com扫描登录后才能使用带有(qzone)的功能,qun.qq.com也一个道理只能用在包含(qun)文字的功能上
