### ISSUE TITLE
木马相关如何正确生成

### ISSUE THREAD

**Issue by audwh** [sun589/QQkey_Tool#6]
stmp服务器以及端口填什么

**Comment by sun589** [comment]
smtp服务器取决于你使用的邮箱,以下是常见的邮箱smtp地址
163:smtp.163.com
qq:smtp.qq.com
126:smtp.126.com
密码那一个框填授权码或者密码,一般是授权码,这种请到网上搜索 你的邮箱品牌(如网易163)+如何获取授权码查询授权码获取教程

**Comment by sun589** [comment]
端口一般是25,不用改

**Comment by sun589** [comment]
根据需求填写完后点开始生成即可,可以自己在电脑上测试是否有效,之后再发给别人测试木马:))))))

**Comment by audwh** [comment]
必须是要电脑打开木马吧

**Comment by sun589** [comment]
对的
